<?php
/**
 * KeySynx — Bulk seed data (5 artists)
 * Source: community key/BPM analysis PDFs uploaded for
 * Ariana Grande, Britney Spears, Harry Styles, Taylor Swift, Bruno Mars.
 *
 * Format per song: [title, bpm|null, key, time_signature|null, footnote|null, sections]
 * sections format: [ [label, key, bpm|null], ... ]  — used for tracks whose
 * key/BPM changes across different parts of the song.
 *
 * NOTE ON SCOPE: this covers everything in the 4 newly-uploaded PDFs in full,
 * plus the rest of the Ariana Grande catalog beyond Eternal Sunshine (which
 * is already seeded separately in schema.sql). A few entries with literally
 * no BPM or no key given in the source were left out rather than guessed
 * (e.g. "Break The Ice" intro/outro split with no key, "Ever Been" with no
 * key) — fabricating data isn't an option even to hit a round number.
 */

return [

  // ============================================================
  'Ariana Grande' => [
    'Dangerous Woman' => [
      ['Moonlight', 102, 'A Major', '12/8', 'Uses some 7th chords', []],
      ['Dangerous Woman', 134, 'G Major', '6/8', null, []],
      ['Be Alright', 109, 'C# Minor', null, null, []],
      ['Into You', 108, 'F# Minor', null, null, []],
      ['Side To Side', 159, 'F# Minor', null, null, []],
      ['Let Me Love You', 139, 'E Minor', null, 'Works well as harmonic minor', []],
      ['Greedy', 110, 'F# Major', null, null, [['0:00-2:36','F# Major',null],['2:37-end','G# Major',null]]],
      ['Leave Me Lonely', 91, 'G# Minor', '6/8', 'Harmonic minor variant', []],
      ['Everyday', 131, 'A# Major', null, null, []],
      ['Sometimes', 80, 'E Major', null, null, []],
      ["I Don't Care", 112, 'C Major', null, null, []],
      ['Bad Decisions', 132, 'G Major', null, null, []],
      ['Touch It', 101, 'G Minor', null, null, []],
      ['Knew Better / Forever Boy', 107, 'C# Major', null, 'BPM shifts to 108 near the end', []],
      ['Thinking Bout You', 103, 'B Major', null, null, []],
      ['Step On Up', 111, 'G Minor', null, null, []],
      ["Jason's Song (Gave It Away)", 106, 'G Minor', null, null, []],
    ],
    'Sweetener' => [
      ['raindrops (an angel cried)', null, 'F# Major', null, 'Unfixed tempo (rubato)', []],
      ['blazed', 110, 'B Mixolydian', null, 'Instrumental verse works as F# root', []],
      ['the light is coming', 99, 'C# Minor', null, 'Alternates between keyless sections and C# Minor', [['Intro/Outro','Keyless (A root)',null],['Verse','C# Minor',null]]],
      ['R.E.M', 80, 'G# Mixolydian', null, 'May work best with F# root', []],
      ['God is a woman', 145, 'D# Minor', null, null, []],
      ['sweetener', 120, 'E Major', null, 'Vocals lean Mixolydian in places', []],
      ['successful', 114, 'C Major', null, 'Verses: vocals D Minor over G Mixolydian instrumental', [['Verses (vocals)','D Minor',null],['Verses (inst)','G Mixolydian',null],['Chorus','C Major',null]]],
      ['everytime', 148, 'A# Minor', null, null, []],
      ['breathin', 100, 'F Minor', null, null, []],
      ['no tears left to cry', 122, 'A Minor', null, 'Intro is rubato (~100-126 BPM)', [['Intro','C Major',101],['Verses/Postchorus','A Melodic Major',122],['Chorus/Bridge','A Minor',122]]],
      ['borderline', 111, 'D Minor', null, null, []],
      ['better off', 92, 'B Major', null, null, []],
      ['goodnight n go', 111, 'C# Major', null, null, []],
      ['pete davidson', 120, 'B Mixolydian', null, 'Uses triplets throughout (still 4/4)', []],
      ['get well soon', 100, 'G Mixolydian', null, 'Borrows Cm from G Minor', []],
    ],
    'thank u, next' => [
      ['imagine', 125, 'Ab Major', '3/4', 'Verses borrow Ebm7 & Ab7', []],
      ['needy', 87, 'Eb Major', null, 'Borrows Amø, AbΔ(b5), Eb7', []],
      ['NASA', 150, 'F# Major', null, null, []],
      ['bloodline', 152, 'D Minor', null, null, []],
      ['fake smile', 85, 'B Minor', null, null, [['Verses & Bridge','B Minor',null],['Rest','D Major',null]]],
      ['bad idea', 138, 'D# Minor', null, null, []],
      ['make up', 140, 'D Mixolydian', null, 'Vocals use triplets in verses', []],
      ['ghostin', 104, 'A Major', null, null, []],
      ['in my head', 135, 'E Minor', null, null, []],
      ['7 rings', 140, 'C# Minor', '12/8', 'Borrows G#maj; better as harmonic minor', []],
      ['thank u, next', 107, 'Db Major', null, null, []],
      ["break up with your girlfriend, i'm bored", 170, 'C Minor', null, null, [['Pre-chorus','C Dorian',null],['Rest','C Minor',null]]],
    ],
    'Positions' => [
      ['shut up', 128, 'C Major', null, null, []],
      ['34+35', 110, 'F Major', null, null, []],
      ['motive (ft. doja cat)', 117, 'A# Minor', null, null, []],
      ['just like magic', 128, 'G# Major', null, null, []],
      ['off the table (ft. the weeknd)', 101, 'C Major', null, null, []],
      ['six thirty', 120, 'C Major', null, null, []],
      ['safety net (ft. ty dolla $ign)', 81, 'C# Minor', null, null, []],
      ['my hair', 92, 'A Minor', null, '"A root" — major/minor ambiguous in source', []],
      ['nasty', 128, 'A Major', null, null, []],
      ['west side', 88, 'B Minor', null, null, []],
      ['love language', 110, 'C Major', null, 'Melodic major; borrows minor coloring', []],
      ['positions', 72, 'D Minor', null, null, []],
      ['obvious', 80, 'C Major', null, null, []],
      ['pov', 132, 'Eb Major', null, null, []],
    ],
    'Positions (Deluxe)' => [
      ['Someone Like You', 118, 'A# Major', null, 'Borrows Bmaj7/C#maj7 throughout', []],
      ['Test Drive', 115, 'A Minor', null, 'Borrows harmonic minor and Gm7', []],
      ['Worst Behavior', 100, 'C Minor', null, null, []],
      ['Main Thing', 134, 'E Mixolydian', null, null, []],
    ],
    'My Everything' => [
      ['Intro', null, 'F# Major', null, 'Tempo unsteady', []],
      ['Problem', 103, 'G# Minor', null, null, []],
      ['One Last Time', 125, 'Ab Major', null, null, []],
      ['Why Try', 160, 'B Major', null, null, []],
      ['Break Free', 130, 'G Minor', null, null, []],
      ['Best Mistake', 144, 'Bb Minor', null, null, []],
      ['Be My Baby', 145, 'D# Minor', null, null, []],
      ['Break Your Heart Right Back', 94, 'D# Minor', null, null, []],
      ['Love Me Harder', 99, 'C# Minor', null, null, []],
      ['Just a Little Bit of Your Heart', 78, 'A Major', null, null, []],
      ['Hands on Me', 97.98, 'B Minor', null, 'Verses/outro lean Phrygian Dominant', []],
      ['My Everything', 62, 'F# Major', null, null, []],
      ['Bang Bang', 150, 'C Minor', null, 'Chorus is C Mixolydian', []],
      ['Only 1', 101.5, 'A Minor', null, null, []],
      ["You Don't Know Me", 170, 'D Minor', null, null, []],
    ],
    'Yours Truly' => [
      ['Honeymoon Avenue', 125, 'F# Mixolydian', null, null, []],
      ['Baby I', 102, 'Db Major', null, null, []],
      ['Right There', 156, 'G Major', null, null, []],
      ['Tattooed Heart', 108, 'G Major', '6/8', null, [['0:00-2:13','G Major',null],['2:13-end','Ab Major',null]]],
      ["Lovin' It", 94, 'E Major', null, null, []],
      ['Piano', 120, 'E Major', null, null, []],
      ["Daydreamin'", 114, 'G Major', '6/8', null, []],
      ['The Way', 82.5, 'Ab Major', null, null, []],
      ["You'll Never Know", 105, 'F# Major', null, null, []],
      ['Almost Is Never Enough', 122.5, 'D Major', '3/4', null, []],
      ['Popular Song', 99, 'Eb Major', null, null, []],
      ['Better Left Unsaid', 130, 'A Major', null, null, []],
    ],
    'Christmas & Chill' => [
      ['December', null, 'F# Minor', null, 'BPM not specified in source', []],
    ],
    'Singles & Features' => [
      ["I Don't Do Drugs", 77, 'F Major', null, null, []],
      ['Met Him Last Night', 145, 'E Minor', null, null, []],
      ['Die For You (Remix)', 134, 'Db Minor', null, null, []],
      ['Save Your Tears (Remix)', 118, 'C Major', null, null, []],
      ['Rain On Me', 123, 'C# Minor', null, null, []],
      ['Bed', 90, 'E Minor', null, null, []],
      ['Rule The World', 88, 'Eb Minor', null, null, []],
      ['Focus', 100, 'B Major', null, null, []],
      ["Don't Call Me Angel", null, 'C Minor', null, null, []],
      ['Bad To You', 148, 'D Minor', null, 'Vocals borrow raised 7th/3rd', []],
      ['How I Look On You', null, 'E Minor', null, null, []],
      ["Got Her Own", null, 'F# Minor', null, 'Section between chorus/drop is neapolitan minor', []],
      ['Santa Tell Me', 96, 'G Major', null, null, []],
      ['Stuck With You', 179, 'G# Major', '6/8', null, []],
      ['Just Look Up', 130, 'A Major', null, 'Two-stage tempo ramp near the start', []],
      ['MONOPOLY', 72, 'A Minor', null, null, []],
      ['boyfriend', 95, 'A# Minor', null, null, []],
      ['Heatstroke', 110, 'Eb Major', null, null, []],
      ['Quit', 135, 'C Minor', null, null, []],
      ['Put Your Hearts Up', 81, 'A Major', null, null, []],
    ],
    'Unreleased' => [
      ['Like That (Jada)', 86.5, 'C# Phrygian Dominant', null, null, []],
      ['Juice', 150, 'C Major', null, null, []],
      ['Ridiculous', 97.5, 'C Minor', '6/8', null, []],
      ['Esta Noche', 107, 'Eb Minor', null, null, []],
      ['In The Moment', 138, 'G Minor', null, 'Borrows C# note', []],
      ["Fuckin' With You", 125, 'D Minor', null, 'Last chorus is E Minor', []],
      ['My Way', 140, 'C# Minor', null, null, []],
      ['That Bitch Is Mine', 134, 'C# Minor', null, 'Vocals lean natural minor', []],
      ['Not Ok', 110, 'G Major', null, null, []],
      ['Remember', 128, 'A# Major', null, 'Borrows Fm7 & Bmaj7', []],
      ['Sex', 115, 'Eb Major', null, null, []],
      ['Outgrown', 94, 'Eb Major', null, null, []],
      ['Real', 156, 'C Minor', null, null, []],
      ['Dream', 158, 'G Minor', null, 'Borrows F#maj throughout', []],
      ['White Tee / Wifey', 138.7, 'E Minor', null, 'Detuned by -50 cents', []],
      ['Fantasize', 94, 'A Minor', null, 'Harmonic minor', []],
      ['Sweet Dreams', 145, 'F Major', null, null, []],
      ['Cocoon', 140, 'G Major', null, null, []],
      ['First Time', 122, 'B Minor', null, 'Borrows Emaj throughout', []],
      ['No Free Promo', 110, 'B Minor', null, null, []],
      ['My Fault', 85, 'Ab Major', null, null, []],
      ['Y Is Everyone So In Love With Me', 83.5, 'B Minor', null, null, []],
      ['Hi', 86, 'C Major', null, 'Borrows Amaj throughout', []],
      ["Don't Talk To My Man", 84, 'E Minor', null, null, []],
      ['He Had It Comin', 125, 'F Minor', null, 'Harmonic minor; borrows Fmaj in chorus', []],
      ['Young Love', 97, 'E Major', null, null, []],
      ['True Story (Unreleased)', 138, 'A Minor', null, 'Harmonic minor', []],
      ['All That', 104, 'C Minor', null, null, []],
      ['Human', 120, 'Bb Minor', null, null, []],
      ['Still On Your Mind', 144, 'Ab Major', null, null, []],
      ['Hate That You Made Me Love You', 93.5, 'G Minor', '6/8', null, []],
      ['What Would You', 85, 'A Minor', null, 'Harmonic minor', []],
      ['Gloss', 90, 'A Minor', null, 'Borrows Emaj', []],
      ['Soul Idea', 98, 'G Major', null, null, []],
    ],
  ],

  // ============================================================
  'Britney Spears' => [
    'Glory' => [
      ['Invitation', 114, 'C# Major', null, null, []],
      ['Make Me...', 123, 'Bb Major', null, null, []],
      ['Private Show', 112.5, 'D Major', '12/8', null, []],
      ['Man On The Moon', 110, 'Bb Major', null, null, []],
      ['Just Luv Me', 92, 'A Minor', null, 'Possibly F Lydian or a mix — needs confirmation', []],
      ['Clumsy', 104, 'F Minor', null, null, []],
      ['Do You Wanna Come Over?', 121, 'E Major', null, null, []],
      ['Slumber Party', 135, 'C Major', null, null, []],
      ['Just Like Me', 102, 'A Minor', null, null, []],
      ['Love Me Down', 99, 'D Minor', null, null, []],
      ['Hard To Forget Ya', 115, 'A Major', null, null, []],
      ['What You Need', 77, 'A Minor', null, null, []],
      ['Better', 97, 'Bb Minor', null, null, []],
      ['Change Your Mind', 118, 'B Minor', null, null, []],
      ['Liar', 80, 'F# Minor', null, null, []],
      ["If I'm Dancing", 124, 'Ab Major', null, null, []],
      ['Coupure Eléctrique', 110, 'C Minor', null, null, []],
      ['Mood Ring', 105, 'Ab Minor', null, null, []],
    ],
    'Femme Fatale' => [
      ['Till The World Ends', 132, 'C Minor', null, null, []],
      ['Gasoline', null, 'B Minor', null, null, []],
    ],
    'Circus' => [
      ['Womanizer', null, 'C# Phrygian', '12/8', null, []],
    ],
    'Blackout' => [
      ['Gimme More', 113.33, 'G Minor', null, 'Detuned by -25 cents', []],
      ['Perfect Lover', 117, 'F# Minor', null, null, []],
    ],
    'Singles & Features' => [
      ['Hold Me Closer', 126, 'A Minor', null, null, []],
    ],
  ],

  // ============================================================
  'Harry Styles' => [
    "Harry's House" => [
      ['Music For A Sushi Restaurant', 107, 'F# Mixolydian', '4/4', 'Borrows D#maj & Dmaj in chorus, A note in horns', [['Intro','F# Minor',null],['Rest','F# Mixolydian',null]]],
      ['Late Night Talking', 115, 'Bb Major', '4/4', 'Borrows D7 throughout, Ebm in chorus', []],
      ['Grapejuice', 91.5, 'F Major', '4/4', null, []],
      ['As It Was', 174, 'A Major', '4/4', null, []],
      ['Daylight', 97, 'C Major', '4/4', null, []],
      ['Little Freak', 142, 'Eb Major', '4/4', null, []],
      ['Matilda', 114, 'D Major', '4/4', 'Borrows F#7 & E7 in bridge', []],
      ['Cinema', 106, 'A Minor', '4/4', null, []],
      ['Daydreaming', 114, 'E Minor', '4/4', 'Bass borrows Eb note', []],
      ['Keep Driving', 165, 'A Major', '12/8', null, []],
      ['Satellite', 139, 'A Minor', '4/4', 'May also work well as C Major', []],
      ['Boyfriends', 88.5, 'C Major', '12/8', 'Briefly borrows D7 in bridge', []],
      ['Love Of My Life', 118, 'G Major', '4/4', 'Borrows Bmaj throughout, Dm in post-chorus', []],
    ],
    'Fine Line' => [
      ['Golden', 140, 'E Minor', null, null, []],
      ['Watermelon Sugar', 95, 'D Dorian', null, 'BPM steps from 95 to 95.5 partway through', []],
      ['Adore You', 99, 'C Minor', null, null, []],
      ['Lights Up', 102, 'Bb Minor', null, 'Borrows Bb major chord; tempo eases later', [['0:00-2:24','Bb Minor',102],['2:24-2:34','Bb Minor',94],['2:34-end','Bb Minor',88]]],
      ['Cherry', 96, 'G Major', null, null, []],
      ['Falling', 110, 'E Major', null, null, []],
      ['To Be So Lonely', 105, 'C Major', '12/8', null, []],
      ['She', 93.33, 'E Minor', '3/4', 'Borrows Dm chord from phrygian; B7#5(#9) as a color chord', []],
      ['Sunflower, Vol. 6', 160, 'F Major', null, 'Chorus is 158 BPM', []],
      ['Canyon Moon', 94, 'D Major', null, null, []],
      ['Treat People With Kindness', 122, 'C Mixolydian', null, null, []],
      ['Fine Line', 121, 'D Major', null, null, []],
    ],
    'Self Titled (Harry Styles)' => [
      ['Meet Me In The Hallway', 103, 'G Major', '4/4', 'Tempo unsteady', []],
      ['Sign Of The Times', 120, 'F Major', '4/4', null, []],
      ['Carolina', 122, 'E Mixolydian', '4/4', 'Shifts to parallel E Minor in choruses', []],
      ['Two Ghosts', 70, 'E Major', '4/4', null, []],
      ['Sweet Creature', 106, 'G Major', '4/4', null, []],
      ['Only Angel', 114, 'E Major', '4/4', 'Intro is F#; recommend starting with C# Minor', []],
      ['Kiwi', 147, 'E Major', '12/8', null, []],
      ['Ever Since New York', 96, 'F Major', '4/4', null, []],
      ['Woman', 147, 'F# Major', '12/8', null, []],
      ['From The Dining Table', 147, 'Eb Major', '4/4', 'Structure/time signature uncertain in places', []],
    ],
  ],

  // ============================================================
  'Taylor Swift' => [
    'Midnights (3am Edition)' => [
      ['Lavender Haze', 97, 'Bb Major', '4/4', null, []],
      ['Maroon', 108, 'G Major', '4/4', null, []],
      ['Anti-Hero', 96.94, 'E Major', '4/4', null, []],
      ['Snow On The Beach (feat. Lana Del Rey)', 110, 'A Major', '4/4', null, []],
      ["You're On Your Own, Kid", 120, 'D Major', '4/4', null, []],
      ['Midnight Rain', 140, 'C Major', '4/4', null, []],
      ['Question...?', 109, 'C Major', '4/4', null, []],
      ['Vigilante Shit', 80, 'A Minor', '4/4', 'Borrows G# from harmonic minor in bridge', []],
      ['Bejeweled', 82, 'C Major', '4/4', null, []],
      ['Labyrinth', 110, 'C Major', '4/4', null, []],
      ['Karma', 90, 'Eb Mixolydian', '4/4', null, []],
      ['Sweet Nothing', 112, 'C Major', '12/8', null, []],
      ['Mastermind', 126, 'E Major', '4/4', null, []],
      ['The Great War', 96, 'Bb Major', '4/4', null, []],
      ['Bigger Than The Whole Sky', 84, 'F# Major', '4/4', null, []],
      ['Paris', 111, 'G Major', '4/4', null, []],
      ['High Infidelity', 88, 'Bb Major', '4/4', null, []],
      ['Glitch', 70, 'A Major', '4/4', null, []],
      ["Would've, Could've, Should've", 79, 'G Major', '4/4', null, []],
      ['Dear Reader', 54, 'C Major', '4/4', null, []],
    ],
    'Self Titled (Taylor Swift)' => [
      ['Tim McGraw', 152, 'C Major', null, null, []],
      ['Picture To Burn', 106, 'G Major', null, null, []],
      ['Teardrops On My Guitar', 100, 'A# Major', null, null, []],
      ['A Place In This World', 115, 'A Major', null, 'Borrows G at end of each chorus', []],
      ['Cold As You', 88, 'F Major', null, null, []],
      ['The Outside', 113, 'F Major', null, null, []],
      ['Tied Together With A Smile', 146, 'D Major', null, null, []],
      ['Stay Beautiful', 132, 'G# Major', null, 'Swing 4/4; borrows A#, bridge Fm', []],
      ["Should've Said No", 84, 'G Major', null, 'Intro/chorus Em, borrows A', []],
      ["Mary's Song (Oh My My My)", 151, 'D Major', null, null, []],
      ['Our Song', 89, 'D Major', null, 'Swing 4/4', []],
      ["I'm Only Me When I'm With You", 144, 'G# Major', null, 'Bridge Fm, borrows A#', []],
      ['Invisible', 96, 'G Major', null, null, []],
      ['A Perfectly Good Heart', 156, 'E Major', null, null, []],
    ],
    "Fearless (Taylor's Version)" => [
      ["Fearless (Taylor's Version)", 100, 'F Major', null, 'Bridge borrows Eb', []],
      ["Fifteen (Taylor's Version)", 95, 'G Major', null, null, []],
      ["Love Story (Taylor's Version)", 119, 'D Major', null, null, [['3:18-end','E Major',null]]],
      ["Hey Stephen (Taylor's Version)", 116, 'F# Major', null, null, []],
      ["White Horse (Taylor's Version)", 92, 'C Major', null, 'End of bridge borrows Bb', []],
      ["You Belong With Me (Taylor's Version)", 130, 'F# Major', null, null, []],
      ["Breathe (feat. Colbie Caillat) (Taylor's Version)", 148, 'C# Major', null, null, []],
      ["Tell Me Why (Taylor's Version)", 100, 'G Major', null, 'Bridge Em, borrows A', []],
      ["You're Not Sorry (Taylor's Version)", 134, 'F# Major', null, 'Chorus borrows Ddim, swing 4/4', []],
      ["The Way I Loved You (Taylor's Version)", 80.5, 'F Major', null, 'Borrows Bbm at several points', []],
      ["Forever & Always (Taylor's Version)", 128, 'Bb Major', null, 'Bridge/outro Gm', []],
      ["The Best Day (Taylor's Version)", 126, 'C# Major', null, null, []],
      ["Change (Taylor's Version)", 96, 'F Major', null, null, []],
      ["Jump Then Fall (Taylor's Version)", 80, 'D Major', null, null, []],
      ["Untouchable (Taylor's Version)", 100, 'F Major', null, 'Ritardando in outro', []],
      ["Forever & Always (Piano Version) (Taylor's Version)", 118.6, 'A Major', null, null, []],
      ["Come In With The Rain (Taylor's Version)", 144, 'D Major', null, 'Chorus borrows Amaj', []],
      ["Superstar (Taylor's Version)", 86, 'D Major', null, null, []],
      ["The Other Side Of The Door (Taylor's Version)", 82, 'E Major', null, 'Borrows Dmaj in prechorus/bridge', []],
      ["Today Was A Fairytale (Taylor's Version)", 79, 'G Major', null, null, []],
      ["You All Over Me (feat. Maren Morris) (Taylor's Version) (From The Vault)", 143, 'D Major', null, null, []],
      ["Mr. Perfectly Fine (From The Vault)", 136, 'D Major', null, null, []],
      ["We Were Happy (From The Vault)", 106, 'C Major', null, null, []],
      ["That's When (feat. Keith Urban) (From The Vault)", 90, 'F Major', null, null, []],
      ["Don't You (From The Vault)", 102, 'D# Major', null, null, []],
      ["Bye Bye Baby (From The Vault)", 80, 'F Major', null, 'Borrows Gmaj in choruses', []],
    ],
    'Speak Now' => [
      ['Mine', 121, 'G Major', null, null, []],
      ['Sparks Fly', 115, 'F Major', null, null, []],
      ['Back to December', 142, 'D Major', null, null, []],
      ['Speak Now', 118.96, 'G Major', null, null, []],
      ['Dear John', 119.5, 'E Major', '3/4', null, []],
      ['Mean', 163.96, 'E Major', null, null, []],
      ['The Story of Us', 140, 'E Major', null, null, []],
      ['Never Grow Up', 125, 'D Major', null, null, []],
      ['Enchanted', 164, 'Ab Major', null, null, []],
      ['Better Than Revenge', 145.5, 'B Minor', null, 'Unfixed tempo', []],
      ['Innocent', 134, 'C# Minor', null, 'Alternates between C# Minor and E Major across the song', [['0:00-1:11','C# Minor',null],['1:11-1:26','E Major',null],['1:26-2:37','C# Minor',null],['2:37-3:06','E Major',null]]],
      ['Haunted', 162.5, 'D Minor', null, 'Unfixed tempo', []],
      ['Last Kiss', 158.93, 'Bb Major', '3/4', null, []],
      ['Long Live', 102, 'G Major', null, null, []],
      ['Ours', 160, 'C Major', null, null, []],
      ['If This Was a Movie', 148, 'E Major', null, null, []],
      ['Superman', 132, 'G Major', null, null, []],
      ['Back to December (Acoustic)', 141.9, 'D Major', null, 'Unfixed tempo', []],
      ['Haunted (Acoustic)', 162, 'D Minor', null, 'Unfixed tempo', []],
    ],
    'Red' => [
      ['State Of Grace', 130, 'E Major', null, null, []],
      ['Red', 125, 'E Major', null, null, []],
      ['Treacherous', 110, 'D Major', null, null, []],
      ['I Knew You Were Trouble', 154, 'Eb Minor', null, null, [['0:00-0:40','Gb Major',null],['0:40-1:18','Eb Minor',null],['1:18-1:55','Gb Major',null],['1:55-end','Eb Minor',null]]],
      ['All Too Well', 93, 'C Major', null, null, []],
      ['22', 104, 'G Major', null, null, []],
      ['I Almost Do', 146, 'E Major', null, null, []],
      ['We Are Never Ever Getting Back Together', 86, 'G Major', null, null, []],
      ['Stay Stay Stay', 100, 'C Major', null, null, []],
      ['The Last Time (feat. Gary Lightbody)', 94, 'D Major', null, null, []],
      ['Holy Ground', 157, 'E Major', null, null, []],
      ['Sad Beautiful Tragic', 131.65, 'G Major', '3/4', null, []],
      ['The Lucky One', 118, 'E Major', null, null, []],
      ['Everything Has Changed', 80, 'Gb Major', null, null, []],
      ['Starlight', 126, 'E Major', null, null, []],
      ['Begin Again', 158, 'G Major', null, null, []],
      ['The Moment I Knew', 126, 'G Major', null, null, []],
      ['Come Back… Be Here', 80, 'E Major', null, null, []],
      ['Girl At Home', 125, 'F Major', null, null, []],
    ],
    '1989' => [
      ['Welcome to New York', 117, 'G Major', null, null, []],
      ['Blank Space', 96, 'F Major', null, null, []],
      ['Style', 95, 'D Major', null, 'Verses are B Minor, choruses are D Major', []],
      ['Out Of The Woods', 92, 'C Major', null, null, []],
      ['All You Had To Do Was Stay', 97, 'F Major', null, null, []],
      ['Shake It Off', 80, 'G Mixolydian', null, null, []],
      ['I Wish You Would', 118, 'C Major', null, null, []],
      ['Bad Blood', 85, 'G Major', null, 'Kendrick Lamar remix version is mostly E Minor', []],
      ['Wildest Dreams', 140, 'Ab Major', null, null, []],
      ['How You Get The Girl', 120, 'F Major', null, null, []],
      ['This Love', 72, 'E Major', null, null, []],
      ['I Know Places', 80, 'A Minor', null, 'Ambiguous between A Minor (verses) and C Major (choruses)', []],
      ['Clean', 104, 'E Major', null, null, []],
      ['Wonderland', 92, 'Eb Major', null, null, []],
      ['You Are In Love', 85, 'A Major', null, null, []],
      ['New Romantics', 122, 'F Major', null, null, []],
    ],
    'Reputation' => [
      ['...Ready For It?', 80, 'E Minor', null, 'Chorus is G Major', []],
      ['End Game', 79.5, 'A Minor', null, null, []],
      ['I Did Something Bad', 83, 'G Minor', null, 'Vocals borrow raised 4th stylistically', []],
      ["Don't Blame Me", 135.5, 'A Minor', '12/8', 'BPM shifts to 136 outside the intro', []],
      ['Delicate', 95, 'C Major', null, null, []],
      ['Look What You Made Me Do', 128, 'A Minor', null, 'Borrows E major chord from harmonic minor', []],
      ['So It Goes', 150, 'D Major', null, null, []],
      ['Gorgeous', 92, 'C Major', null, null, []],
      ['Getaway Car', 86, 'C Major', null, null, [['0:00-2:17','C Major',null],['2:17-end','D Major',null]]],
      ['King Of My Heart', 110, 'C Major', null, null, []],
      ["Dancing With Our Hands Tied", 80, 'C Minor', null, null, []],
      ['Dress', 120, 'C Major', null, null, []],
      ["This Is Why We Can't Have Nice Things", 82, 'F Mixolydian', null, 'Verses F Mixolydian, rest F Major; lots of triplets', []],
      ['Call It What You Want', 82, 'A Major', null, null, []],
      ["New Year's Day", 94, 'C Major', null, 'Unfixed tempo', []],
    ],
    'Lover' => [
      ['I Forgot That You Existed', 95, 'F Major', null, 'Bridge is D Minor', []],
      ['Cruel Summer', 85, 'A Major', null, 'Verses are F# Minor', []],
      ['Lover', 102.75, 'G Major', '6/8', 'Bridge borrows F from mixolydian', []],
      ['The Man', 110, 'A Minor', null, 'Works equally well as C Major', []],
      ['The Archer', 125, 'C Major', null, 'Verses are A Minor', []],
      ['I Think He Knows', 100, 'Bb Major', null, null, []],
      ['Miss Americana & The Heartbreak Prince', 75, 'B Minor', null, null, []],
      ['Paper Rings', 104, 'D Major', null, null, [['0:00-1:55','D Major',null],['1:55-end','E Major',null]]],
      ['Cornelia Street', 102, 'C Major', null, 'Prechorus and bridge are A Minor', []],
      ['Death By A Thousand Cuts', 94, 'E Major', null, null, []],
      ['London Boy', 79, 'F# Major', null, null, []],
      ["Soon You'll Get Better", 104, 'C Major', null, 'Borrows Fm near the end of the bridge', []],
      ['False God', 80, 'B Minor', null, 'Chorus and intro are D Major', []],
      ['You Need To Calm Down', 85, 'D Major', null, null, []],
      ['Afterglow', 111, 'A Major', null, null, []],
      ['ME! (feat. Brendon Urie)', null, 'C Major', null, 'Detuned +18 cents approximately', []],
      ["It's Nice To Have A Friend", 140, 'Bb Major', null, null, []],
      ['Daylight (Lover)', 75, 'C Major', null, null, []],
    ],
    'folklore' => [
      ['the 1', 140, 'C Major', null, null, []],
      ['cardigan', 130, 'Eb Major', '12/8', null, []],
      ['the last great american dynasty', 148, 'G Major', null, null, []],
      ['exile', 152, 'F# Major', null, 'Tempo drifts gradually across the song (roughly 143-153 BPM)', []],
      ['my tears ricochet', 130, 'A Minor', null, null, []],
      ['mirrorball', 110, 'D Major', null, null, []],
      ['seven', 95, 'B Mixolydian', null, null, [['0:00-1:22','B Mixolydian',null],['1:22-1:53','C# Minor',null],['1:53-2:44','B Mixolydian',null],['2:44-end','C# Minor',null]]],
      ['august', 90, 'F Major', null, null, []],
      ['this is me trying', 136, 'A Major', null, null, []],
      ['illicit affairs', 120, 'Bb Major', null, null, []],
      ['invisible string', 83.5, 'D Major', null, 'Borrows chords from D Mixolydian', []],
      ['mad woman', 142, 'C Minor', null, null, []],
      ['epiphany', 93, 'Db Major', null, null, []],
      ['betty', 96, 'C Major', null, null, [['Chorus & Verses','C Major',null],['Prechorus & Bridge','A Minor',null],['Last Chorus','D Major',null]]],
      ['peace', 150, 'F Major', null, null, []],
      ['hoax', 119, 'Ab Major', '12/8', 'Unfixed tempo', []],
    ],
    'evermore' => [
      ['willow', 84, 'E Minor', null, 'Chorus is G Major', []],
      ['champagne problems', 86, 'C Major', null, null, []],
      ['gold rush', 112, 'A Major', null, 'Chorus is A Mixolydian', []],
      ["'tis the damn season", 146, 'F Major', null, 'Works equally well as D Minor', []],
      ['tolerate it', 75, 'A Major', '5/4', 'Bridge is F# Minor', []],
      ['no body, no crime', 79, 'G Minor', null, 'Bridge borrows D from harmonic minor', []],
      ['happiness', 122, 'B Major', null, 'Bridge moves through B Mixolydian/E Major into C# Minor', []],
      ['dorothea', 120, 'E Major', '12/8', null, []],
      ['coney island', 108, 'Ab Major', null, null, []],
      ['ivy', 89, 'D Major', null, '1:51-2:12 is B Minor', []],
      ['cowboy like me', 128, 'C Major', null, 'Bridge is A Dorian', []],
      ['long story short', 158, 'C Major', null, 'Bridge is A Minor', []],
      ['marjorie', 96, 'F Major', null, null, []],
      ['closure', 152, 'A Major', '5/4', null, []],
      ['evermore', 100, 'C# Major', null, 'Tempo steps up to 121 then settles around 104', [['0:00-2:37','C# Major',100],['2:37-3:42','C# Major',121],['3:42-end','C# Major',104]]],
    ],
  ],

  // ============================================================
  'Bruno Mars' => [
    'Unorthodox Jukebox' => [
      ['Young Girls', 126, 'A Major', null, null, []],
      ['Locked Out of Heaven', 144, 'D Minor', null, null, []],
      ['Gorilla', 140, 'B Minor', null, 'Verses B Minor, choruses D Mixolydian, bridge B Minor', []],
      ['Treasure', 116, 'C Minor', null, null, []],
      ['Moonshine', 105, 'A Minor', null, 'Borrows dorian/harmonic minor/phrygian throughout', []],
      ['When I Was Your Man', 146, 'A Minor', null, 'Prechorus borrows Bb; bridge borrows D dorian', []],
      ['Natalie', 112, 'D Minor', null, 'Bridge borrows Bø', []],
      ['Show Me', 156, 'C Mixolydian', null, 'Intro (first 2 seconds) is rubato', []],
      ['Money Make Her Smile', 93, 'E Minor', null, 'Bridge is E Phrygian', []],
      ['If I Knew', 88, 'Eb Major', '6/8', 'BPM shifts to ~82 around 1:56; bridge is C Minor', []],
    ],
    'Doo-Wops & Hooligans' => [
      ['Grenade', 110.5, 'D Minor', null, null, []],
      ['Just The Way You Are', 109, 'F Major', null, null, []],
      ['Our First Time', 156, 'D Dorian', null, 'Borrows D harmonic minor throughout', []],
      ['Runaway Baby', 82, 'D# Minor', null, 'Actual BPM is 164, halved here; chorus borrows harmonic minor', []],
      ['The Lazy Song', 87.5, 'B Major', null, null, []],
      ['Marry You', 145, 'F Major', null, null, []],
      ['Talking To The Moon', 146, 'C# Minor', null, 'Works equally well as E Major', []],
      ['Liquor Store Blues (feat. Damian Marley)', 151, 'C# Minor', null, null, []],
      ['Count on Me', 89, 'C Major', null, 'Bridge instrumental is relative minor (A Minor)', []],
      ['The Other Side (feat. CeeLo Green & B.o.B.)', 140, 'F Minor', null, null, []],
      ['Somewhere in Brooklyn', 130, 'Bb Major', null, 'Intro tempo is unstable/rubato', []],
    ],
    '24K Magic' => [
      ['24K Magic', 107, 'F Minor', null, null, []],
      ['Versace On The Floor', 174, 'D Major', null, null, [['0:00-3:17','D Major',null],['3:17-4:02','Eb Major',null],['4:02-end','E Major',null]]],
      ["That's What I Like", 134, 'Bb Minor', null, null, []],
      ['Chunky', 101, 'C Minor', null, null, []],
      ['Calling All My Lovelies', 160, 'E Major', null, 'Sometimes uses C major chords; intro/outro lean A Mixolydian', [['0:00-2:36','E Major',null],['2:36-2:48','G Major',null],['2:48-end','E Major',null]]],
      ['Too Good To Say Goodbye', 154, 'A Major', null, null, []],
      ['Finesse', 105, 'F Minor', null, null, []],
      ['Straight Up & Down', 144, 'Db Major', null, null, []],
      ['Perm', 124, 'G Minor', null, null, []],
    ],
  ],

];
